// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHzdg6W_nb7y50VyQOmcA2lDFTe5VKg2o',
    appId: '1:399481812665:web:14e20c736c0f7efb0d4d68',
    messagingSenderId: '399481812665',
    projectId: 'fir-test-project-52282',
    authDomain: 'fir-test-project-52282.firebaseapp.com',
    storageBucket: 'fir-test-project-52282.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRe268AwXkyob_lvC0_hhfvqSJxO9x4Y',
    appId: '1:399481812665:android:8d7bb0bc18e16d790d4d68',
    messagingSenderId: '399481812665',
    projectId: 'fir-test-project-52282',
    storageBucket: 'fir-test-project-52282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQkoEx_1qmVTISLWMuOeep5W55ngiwOGI',
    appId: '1:399481812665:ios:86f80c879ef0ad000d4d68',
    messagingSenderId: '399481812665',
    projectId: 'fir-test-project-52282',
    storageBucket: 'fir-test-project-52282.appspot.com',
    iosClientId: '399481812665-15kjv0drj9a25b0a1o910iobnk0vmecm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dependencyinjection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQkoEx_1qmVTISLWMuOeep5W55ngiwOGI',
    appId: '1:399481812665:ios:86f80c879ef0ad000d4d68',
    messagingSenderId: '399481812665',
    projectId: 'fir-test-project-52282',
    storageBucket: 'fir-test-project-52282.appspot.com',
    iosClientId: '399481812665-15kjv0drj9a25b0a1o910iobnk0vmecm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dependencyinjection',
  );
}
